# Generated by Django 5.0 on 2023-12-23 13:07

import localflavor.in_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='NY', max_length=2),
        ),
    ]
